#!/bin/bash -eu

QEMU_VERSION=v10.1.2

if ! [ -d qemu ] ; then
	git clone --branch "${QEMU_VERSION}" --single-branch https://gitlab.com/qemu-project/qemu.git qemu
fi

# sudo apt install -y python3 python3-venv ninja-build libglib2.0-dev libpixman-1-dev libgtk-3-dev git

rm -rf qemu/build
mkdir qemu/build
cd qemu/build

../configure \
	--target-list=aarch64-softmmu \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib/x86_64-linux-gnu \
	--libexecdir=/usr/lib/qemu \
	--firmwarepath=/usr/share/qemu:/usr/share/seabios:/usr/lib/ipxe/qemu \
	--localstatedir=/var \
	--mandir=/usr/share/man \
	\
	--disable-install-blobs \
	--disable-strip \
	--disable-containers \
	--disable-relocatable \
	--disable-docs  \
	--disable-xkbcommon \
	--disable-user \
	--disable-linux-user \
	--disable-xen \
	--disable-sndio \
	\
	--enable-gtk  \
	--enable-slirp

make -j"$(getconf _NPROCESSORS_ONLN)" 2>&1 | tee build-qemu.log
