#!/usr/bin/env python3
#
# Parse a Raspberry Pi config.txt file
#

import argparse
import json

from src.qemu_raspi import config_txt, log

parser = argparse.ArgumentParser()
parser.add_argument("--verbose", action="store_true")
parser.add_argument("--debug", action="store_true")
parser.add_argument("--tryboot", default=False, action="store_true")
parser.add_argument("--model", required=True, choices=["pi4", "pi3"])
parser.add_argument("config_txt")
args = parser.parse_args()

log.enable_logging(verbose=args.verbose, debug=args.debug)

config = config_txt.parse(args.config_txt, model=args.model, tryboot=args.tryboot)
print(json.dumps(config, indent=4))
